/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;
import Graph.*;
import Success.*;
/**
 *
 * @author almohri
 */
public class Main {
    public static void main(String[] args){
        GraphReader reader = new GraphReader();
        Graph g;
        try {
            path = args[0];
        }
        catch(Exception e) {
           System.out.println("Please enter the path to attack graph source files (generated by MulVAL).");  
        }
        g = reader.readGraph(path, 1, true);
        System.out.println("Read a total of "+g.vertices.size()+" vertices.");
        System.out.println("Read a total of "+g.totalFactNodes()+" fact vertices.");
        
        
        InitialSolution init = new InitialSolution();
        init.findInitialSolution(g,path);
        
        SLP slp = new SLP();
        slp.solve(path, g);
    }
}
